Greenpastures/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from graphene_django.views import GraphQLView
from blog.schema import schema


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('about/', include('about.urls')),
    path('contact/', include('contact.urls')),
    path('store/', include('store.urls')),
    path('graphql/', GraphQLView.as_view(graphiql=True)),
    path('account/', include('account.urls')),
    path('blog/', include('blog.urls')),
]
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

about/urls.py
from django.urls import path
from . import views
from about.views import about

app_name = 'about'

urlpatterns = [
path('about/', about, name="about"),
]

blog/urls.py
from django.urls import path
from . import views
from .views import blog, search, CategoryView, blogdetail

app_name='blog'

urlpatterns = [
path('blog/', blog.as_view(), name="blog"),
path('search/', search, name="search"),
path('category/<str:cats>/', CategoryView, name="category"),
path('<slug:slug>/send-comment', views.send_comment, name="send_comment"),
path('<slug:slug>/', blogdetail.as_view(), name="blog-detail"),
]

contact/urls.py
from django.urls import path
from . import views
from contact.views import contact_us, thanks

app_name = 'contact'

urlpatterns = [
path('contact/', contact_us, name="contact_us"),
path('thanks/', thanks, name='thanks'),
]

home/urls.py
from django.urls import path
from home.views import home

app_name = 'home'

urlpatterns = [
path('', home.as_view() , name='index'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime, date
from ckeditor.fields import RichTextField
from django.db.models.base import Model
from django.db.models.signals import pre_save
from Greenpastures.utils import unique_slug_generator

# Create your models here.
class PostComment(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    message = models.TextField()
    create_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.sender.get_username()}'

class Categories(models.Model):
    categoryname = models.CharField(max_length=255)

    def __str__(self):
        return self.categoryname

class Post(models.Model):
    title = models.CharField(max_length=255)
    title_tag = models.CharField(max_length=255, default='Blog Post')
    slug = models.SlugField(max_length=255, null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    img = models.ImageField(upload_to='blog', null=True)
    body = RichTextField(blank=False, null=True)
    comments = models.ManyToManyField(PostComment, blank=True)
    post_date = models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey(Categories, null=True, on_delete=models.PROTECT, related_name='category_set')

    def __str__(self):
        return self.title + ' | ' + str(self.author)

def slug_generator(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)

pre_save.connect(slug_generator, sender=Post)

blog/views.py
from django.http.response import HttpResponse
from django.shortcuts import redirect, render
from django.views.generic import ListView, DetailView
from .models import Post, Categories, PostComment
from home.models import Livestream
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import AnonymousUser
from django.core.paginator import Paginator
from django.http import HttpResponseNotFound, Http404

# Create your views here.

class index(ListView):
   model = Livestream
   template_name = ' blog/base.html'
   context_object_name = 'Livestream'

   def get_context_data(self, *args, **kwargs):
      context = super(home, self).get_context_data(*args, **kwargs)
      return context


class blog(ListView):
   model = Post
   template_name = 'blog/blog_list.html'
   context_object_name = 'posts'
   cats = Categories.objects.all()

   ordering = ['-post_date']  
   paginate_by = 2

   def get_context_data(self, *args, **kwargs):
      cat_list = Categories.objects.all()
      latestpost_list = Post.objects.all().order_by('-post_date')[:3]
      context = super(blog, self).get_context_data(*args, **kwargs)
      context["cat_list"] = cat_list
      context["latestpost_list"] = latestpost_list
      return context


def search(request):
   template = 'blog/search_list.html'
   query = request.GET.get('q')
   if query:
      posts = Post.objects.filter(Q(title__icontains=query) | Q(body__icontains=query)).order_by('-post_date')
   else:
      posts = Post.objects.all()
   
   cat_list = Categories.objects.all()
   latestpost_list = Post.objects.all().order_by('-post_date')[:3]
   paginator = Paginator(posts, 2)
   page = request.GET.get('page')
   posts = paginator.get_page(page)
   return render(request, template, {'posts':posts, 'cat_list': cat_list, 'latestpost_list':latestpost_list, 'query':query})

def CategoryView(request, cats):
   if Categories.objects.filter(categoryname=cats).exists():
      category_posts = Post.objects.filter(category__categoryname=cats).order_by('-post_date')
      cat_list = Categories.objects.all()
      latestpost_list = Post.objects.all().order_by('-post_date')[:3]
      paginator = Paginator(category_posts, 2)
      page = request.GET.get('page')
      category_posts = paginator.get_page(page)
      return render(request, 'blog/category_list.html', {'cats':cats, 'category_posts':category_posts, 'cat_list': cat_list, 'latestpost_list':latestpost_list})
   else:
      raise Http404

class blogdetail(DetailView):
   model = Post
   template_name = 'blog/blog_detail.html'

   def get_context_data(self, *args, **kwargs):
      cat_list = Categories.objects.all()
      latestpost_list = Post.objects.all().order_by('-post_date')[:3]
      context = super(blogdetail, self).get_context_data(*args, **kwargs)
      context["cat_list"] = cat_list
      context["latestpost_list"] = latestpost_list
      return context

def send_comment(request, slug):
    if request.method == "POST":
        message = request.POST.get('message')
        post_id = request.POST.get('post_id')

        # Handle anonymous users
        sender = None if isinstance(request.user, AnonymousUser) else request.user

        post_comment = PostComment.objects.create(sender=sender, message=message)

        post = Post.objects.filter(id=post_id).first()
        if post:
            post.comments.add(post_comment)

    return redirect('.')

templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!-- Favicon -->
    <link href="https://fonts.googleapis.com/css?family=Grand+Hotel" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Fira+Sans:100,200,300,400,700" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700" rel="stylesheet" />

    <link rel="stylesheet" href="{% static 'css/animate.css' %}" />
    <link rel="stylesheet" href="{% static 'css/icomoon.css' %}" />
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" />
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}" />
    <link rel="stylesheet" href="{% static 'css/flexslider.css' %}" />
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}" />
    <link rel="stylesheet" href="{% static 'fonts/flaticon/font/flaticon.css' %}" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <script src="{% static 'js/modernizr-2.6.2.min.js' %}"></script>

    <!-- Favicon -->

    <link rel="stylesheet" href="{% static 'style.css' %}" />
    <link rel="icon" href="{% static 'img/core-img/favicon.ico' %}" />
    <link rel="stylesheet" href="{% static 'vendors/linericon/style.css' %}" />
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" />
    <link rel="stylesheet" href="{% static 'vendors/owl-carousel/owl.carousel.min.css' %}" />
    <link rel="stylesheet" href="{% static 'vendors/nice-select/css/nice-select.css' %}" />
    <link rel="stylesheet" href="{% static 'vendors/animate-css/animate.css' %}" />
    <link rel="stylesheet" href="{% static 'vendors/jquery-ui/jquery-ui.css' %}" />

    {% block title %}
    <title>Blog App</title>
    {% endblock %}
  </head>
  <body>
    <!-- ##### Preloader ##### -->
    <div class="preloader d-flex align-items-center justify-content-center">
      <!-- Line -->
      <div class="line-preloader"></div>
    </div>

    <!-- ##### Header Area Start ##### -->
    <header class="header-area">
      <!-- ***** Top Header Area ***** -->
      <div class="top-header">
        <div class="container">
          <div class="row">
            <div class="col-12">
              <div class="top-header-content d-flex flex-wrap align-items-center justify-content-between">
                <!-- Top Header Meta -->
                <div class="top-header-meta d-flex flex-wrap">
                  <a href="#" class="open" data-toggle="tooltip" data-placement="bottom" title="10 Am to 6 PM"><i class="fa fa-clock-o" aria-hidden="true"></i> <span>Opening Hours; Tue - Fri: 10.00am - 03.00pm</span></a>
                  <!-- Social Info -->
                  <div class="top-social-info">
                    <a href="https://web.facebook.com/sam.ocheja"><i class="fa fa-facebook" aria-hidden="true"></i></a>
                    <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
                    <a href="https://www.youtube.com/channel/UCEzGoOBUQvPKucmqvFc6Qqg/featured"><i class="fa fa-youtube" aria-hidden="true"></i></a>
                  </div>
                </div>
                <!-- Top Header Meta -->
                <div class="top-header-meta">
                  <a href="mailto:info.deercreative@gmail.com" class="email-address"><i class="fa fa-envelope" aria-hidden="true"></i> <span>evergreenpastures23@yahoo.com</span></a>
                  <a href="#" class="phone"><i class="fa fa-phone" aria-hidden="true"></i> <span>+234 (813) 791-5736</span></a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- ***** Top Header Area ***** -->

      <!-- ***** Navbar Area ***** -->
      <div class="crose-main-menu">
        <div class="classy-nav-container breakpoint-off">
          <div class="container">
            <!-- Menu -->
            <nav class="classy-navbar justify-content-between" id="croseNav">
              <!-- Nav brand -->
              <a href="index.html" class="navbar-brand">
                <img src="{% static 'images/logo.png' %}" alt="Logo" class="img-fluid" style="max-height: 60px" />
              </a>
              <!-- Navbar Toggler -->
              <div class="classy-navbar-toggler">
                <span class="navbarToggler"><span></span><span></span><span></span></span>
              </div>

              <!-- Menu -->
              <div class="classy-menu">
                <!-- close btn -->
                <div class="classycloseIcon">
                  <div class="cross-wrap"><span class="top"></span><span class="bottom"></span></div>
                </div>

                <!-- Nav Start -->
                <div class="classynav">
                  <ul>
                    <li><a href="{% url 'home:index' %}">Home</a></li>
                    <li><a href="{% url 'about:about' %}">About</a></li>
                    <li><a href="{% url 'blog:blog' %}">Blog</a></li>
                    <li><a href="{% url 'contact:contact_us' %}">Contact</a></li>
                  </ul>

                  <!-- Search Button -->
                  <div id="header-search"><i class="fa fa-search" aria-hidden="true"></i></div>

                  <a data-toggle="modal" data-target="#partner" class="btn crose-btn header-btn" href="#">BECOME A PARTNER</a>
                </div>
                <!-- Nav End -->
              </div>
            </nav>
          </div>
        </div>

        <!-- ***** Search Form Area ***** -->
        <div class="search-form-area">
          <div class="container">
            <div class="row align-items-center">
              <div class="col-12">
                <div class="searchForm">
                  <form action="{% url 'blog:search' %}" method="GET">
                    <input type="search" aria-label="Search" name="q" value="{{request.GET.q}}" placeholder="Enter keywords &amp; hit enter..." />
                    <button type="submit" class="d-none"></button>
                  </form>
                  <div class="close-icon" id="searchCloseIcon"><i class="fa fa-close" aria-hidden="true"></i></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- ***** Navbar Area ***** -->
    </header>
    <!-- ##### Header Area End ##### -->

    {% block content %} {% endblock %}
  </body>

  <!-- ##### Footer Area End ##### -->

  <!-- ##### All Javascript Script ##### -->
  <script src="{% static 'js/jquery/jquery-2.2.4.min.js' %}"></script>
  <!-- Popper js -->
  <script src="{% static 'js/bootstrap/popper.min.js' %}"></script>
  <!-- Bootstrap js -->
  <script src="{% static 'js/bootstrap/bootstrap.min.js' %}"></script>
  <!-- All Plugins js -->
  <script src="{% static 'js/plugins/plugins.js' %}"></script>
  <!-- Active js -->
  <script src="{% static 'js/active.js' %}"></script>

  <!-- jQuery -->
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <!-- jQuery Easing -->
  <script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
  <!-- Bootstrap -->
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <!-- Waypoints -->
  <script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
  <!-- Flexslider -->
  <script src="{% static 'js/jquery.flexslider-min.js' %}"></script>
  <!-- Owl carousel -->
  <script src="{% static 'js/owl.carousel.min.js' %}"></script>
  <!-- Magnific Popup -->
  <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
  <script src="{% static 'js/magnific-popup-options.js' %}"></script>
  <!-- Main -->
  <script src="{% static 'js/main.js' %}"></script>
</html>

templates/blog/blog_detail.html
{% extends 'blog/base.html' %} {% block title %}
<title>{{ post.title_tag }}</title>
{% endblock %} {% block content %}
<div id="colorlib-container">
  <div class="container">
    <div class="row">
      <div class="col-md-10 col-md-offset-1">
        <article class="blog-entry">
          <div class="blog-wrap">
            <span class="category text-center"> <a href="#">Production:</a> | <a href="#">{{ post.category }}</a> </span>
            <h2 class="text-center"><a href="#">{{ post.title }}</a></h2>

            <div class="blog-image">
              <div class="owl-carousel owl-carousel2 blog-item">
                <div class="item">
                  <a href="#" class="blog image-popup-link" style="background-image: url('{{ post.img.url }}');"></a>
                </div>
                <div class="item">
                  <a href="#" class="blog image-popup-link" style="background-image: url('{{ post.img.url }}');"></a>
                </div>
              </div>

              <ul class="share">
                <li class="text-vertical"><i class="icon-share3"></i></li>
                <li>
                  <a href="#"><i class="icon-facebook"></i></a>
                </li>
                <li>
                  <a href="#"><i class="icon-twitter"></i></a>
                </li>
                <li>
                  <a href="#"><i class="icon-googleplus"></i></a>
                </li>
              </ul>
            </div>

            <span class="category text-center">
              <a href="#"><i class="icon-calendar3"></i> {{ post.post_date|date:'d F y' }}</a> | <a href="#" class="posted-by"><i class="icon-user2"></i> by {{ post.author.first_name }}</a> |
              <a href="#"><i class="icon-bubble3"></i> {{ post.comments.count }} Comments</a>
            </span>

            <div class="desc">
              <p class="first-letra">{{ post.body|safe }}</p>
            </div>
          </div>
        </article>

        <!-- Comment Form -->
        <div class="form-group">
          <div class="contact-form-area">
            <form action="{% url 'blog:send_comment' post.slug %}" method="POST">
              {% csrf_token %}
              <input type="hidden" name="post_id" value="{{ post.id }}" />

              {% if not request.user.is_authenticated %}
              <div class="form-group">
                <input type="text" class="form-control" name="guest_name" placeholder="Your Name" required />
              </div>
              <div class="form-group">
                <input type="email" class="form-control" name="guest_email" placeholder="Your Email (optional)" />
              </div>
              {% endif %}

              <textarea class="form-control" name="message" id="message" cols="30" rows="10" placeholder="Message" required></textarea><br />
              <button type="submit" class="btn-primary btn-custom" style="background-color: #f6490d; border-color: #f6490d; font-style: normal">Add Comment</button>
            </form>
          </div>
        </div>

        <!-- Comment Section -->
        <div class="comment-box">
          <h2 class="colorlib-heading-2">{{ post.comments.count }} Comments</h2>
          {% for comment in post.comments.all %}
          <div class="comment-post">
            <div class="user"></div>
            <div class="desc">
              <h3>
                {% if comment.sender %} {{ comment.sender.first_name }} {% elif comment.guest_name %} {{ comment.guest_name }} <small>(Guest)</small>
                {% else %} Anonymous {% endif %}
                <span>{{ comment.created_at|date:'d M Y, H:i' }}</span>
              </h3>
              <p>{{ comment.message }}</p>
            </div>
          </div>
          {% empty %}
          <div class="alert alert-danger">There is no comment</div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/blog/blog_list.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
 <div>
    <div id="colorlib-container">
      <div class="container">
          <div class="content">
{% for post in posts %}

            <article class="blog-entry">
              <div class="blog-wrap">
                <span class="category text-center"><a href="blog.html">Production:</a> | <a href="blog.html">{{post.category}}</a></span>
                <h2 class="text-center"><a href="{% url 'blog:blog-detail' post.slug %}">{{post.title}}</a></h2>
                <div class="blog-image">
                  <div class="owl-carousel owl-carousel2 blog-item">
                    <div class="item">
                      <a href="{% url 'blog:blog-detail' post.slug %}" class="blog image-popup-link" style="background-image: url('{{post.img.url}}');">
                      </a>
                    </div>
                    <div class="item">
                      <a href="{% url 'blog:blog-detail' post.slug %}" class="blog image-popup-link" style="background-image: url('{{post.img.url}}');">
                      </a>
                    </div>
                  </div>
                </div>
                <span class="category text-center"><a href=""><i class="icon-calendar3"></i> {{post.post_date | date:'d F y'}}</a> | <a href="" class="posted-by"><i class="icon-user2"></i> by {{post.author.first_name}}</a> | <a href=""><i class="icon-bubble3"></i> {{ post.comments.all.count }} Comments</a></span>
              </div>
              <div class="desc">
                <p class="first-letra">{{post.body | slice:':450' | safe}} </p>
              </div>
              <p class="text-center"><a href="{% url 'blog:blog-detail' post.slug %}" class="btn-primary btn-custom" style="background-color:#f6490d; border-color: #f6490d;">Continue Reading</a></p>
            </article>
           
           
    {% endfor %}
    <div>
          <nav aria-label="...">
            <ul class="pagination">
            {% if is_paginated %}
              {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link" style="color:black" href="?page=1"><i class="fa fa-arrow-left" aria-hidden="true"></i></a></li>
                <li class="page-item"><a class="page-link" style="color:black" href="?page={{ page_obj.previous_page_number }}"><i class="fa fa-angle-left" aria-hidden="true"></i></a></li>
              {% endif %}
              {% for num in page_obj.paginator.page_range %}
                {% if num == page_obj.number %}
                  <li class="page-item active"><a class="page-link" style="color:#ffffff; background-color: black; border-color: black;" href="?page={{num}}">{{num}}</a></li>
                {% elif num > page_obj.number|add:'-2' and num < page_obj.number|add:'2' %}
                  <li class="page-item"><a class="page-link" style="color:black" href="?page={{num}}">{{num}}</a></li>
                {% endif %}
              {% endfor %}
              {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link" style="color:black" href="?page={{page_obj.next_page_number}}"><i class="fa fa-angle-right" aria-hidden="true"></i></a></li>
                <li class="page-item"><a class="page-link" style="color:black" href="?page={{ page_obj.paginator.num_pages }}"><i class="fa fa-arrow-right" aria-hidden="true"></i></a></li>
              {% endif %}
            {% endif %}
            </ul>
          </nav>
          </div>
        </div>
        {% block sidebar %}
          <aside class="sidebar">
            <div class="side">
              <div class="form-group">
                <form action="{% url 'blog:search' %}" method="GET">
                <input type="text" class="form-control" name="q" value="{{request.GET.q}}" placeholder="Enter keywords &amp; hit enter....">
                <button type="submit" class="btn btn-primary"><i class="icon-search3"></i></button>
                </form>
              </div>
            </div>
            <div class="side-wrap">
              <h2 class="sidebar-heading">About Me</h2>
              <div class="author-img" style="background-image: url('/static/img/bg-img/about.JPG');"></div>
              <p> <strong>Dr. Samuel David Ocheja</strong> the presiding Archbishop and founder of the Spirit of Life ministry International Incorporated and the senior Pastor of Green Pastures Assembly.  </p>
              <p>
                <ul class="colorlib-social-icons">
                  <li><a href="#"><i class="icon-twitter"></i></a></li>
                  <li><a href="#"><i class="icon-facebook"></i></a></li>
                  <li><a href="#"><i class="icon-linkedin"></i></a></li>
                  <li><a href="#"><i class="icon-dribbble"></i></a></li>
                </ul>
              </p>
            </div>
            <div class="side-wrap">
              <h2 class="sidebar-heading">Recent Post</h2>

              {% for post in latestpost_list %}
              <div class="f-entry">
                <a href="{% url 'blog:blog-detail' post.slug %}" class="featured-img" style="background-image: url('{{post.img.url}}');"></a>
                <div class="desc">
                  <span><i class="icon-calendar3"></i> {{post.post_date| date:'d F y'}}</span>
                  <h3><a href="{% url 'blog:blog-detail' post.slug %}">{{post.title}}</a></h3>
                  <h3><a href="#"></a></h3>
                </div>
              </div>
              {% endfor %}
             
            </div>

            <div class="side-wrap">
              <h2 class="sidebar-heading">Categories</h2>
              <ul class="category">
                {% for categories in cat_list %}
                <li><a href="{% url 'blog:category' categories %}"><span class="badge bg-dark">{{categories.category_set.count}}</span><i class="icon-check"></i>{{categories}}</a> </li>
                    {% endfor %}
              </ul>
            </div>

        
            <div class="side-wrap">
              <h2 class="sidebar-heading">Live stream</h2>
              {% for Livestream in Livestream %}
              <div class=" colorlib-video" style="background-image: url('{{ Livestream.Livestream_Image.url }}');">
                <a href="{{ Livestream.Livestream_URL }}" class="popup-vimeo"><i class="icon-play"></i></a>
                <div class="overlay"></div>
              </div>
              <h4 style="color: #000">{{ Livestream.Livestream_Title }}</h4>

               {% endfor %}
             </div>

            <div class="side-wrap">
              <h2 class="sidebar-heading">Tags</h2>
                <p class="tags">
                  <div class="button-cuz"><p>
                    {% for categories in cat_list %}
                      <span><a href="{% url 'blog:category' categories %}"><i class="icon-tag"></i>{{categories}}</a></span>
                       {% endfor %}
                    </p>
                  </div>
               </p>
            </div>
            <div class="side-wrap">
              <h2 class="sidebar-heading">Gallery</h2>
              <a href="{% static 'images/gallery-1.jpeg' %}" class="gallery image-popup-link text-center" style="background-image: url( '/static/images/gallery-1.jpeg');">
                <span><i class="icon-search3"></i></span>
              </a>
              <a href="{% static 'images/gallery-2.jpeg' %}" class="gallery image-popup-link text-center" style="background-image: url('/static/images/gallery-2.jpeg');">
                <span><i class="icon-search3"></i></span>
              </a>
              <a href="{% static 'images/gallery-3.jpeg' %}" class="gallery image-popup-link text-center" style="background-image: url('/static/images/gallery-3.jpeg');">
                <span><i class="icon-search3"></i></span>
              </a>
              <a href="{% static 'images/gallery-4.jpeg' %}" class="gallery image-popup-link text-center" style="background-image: url('/static/images/gallery-4.jpeg');">
                <span><i class="icon-search3"></i></span>
              </a>
              <a href="{% static 'images/gallery-5.jpeg' %}" class="gallery image-popup-link text-center" style="background-image: url('/static/images/gallery-5.jpeg');">
                <span><i class="icon-search3"></i></span>
              </a>
              <a href="{% static 'images/gallery-6.jpeg' %}" class="gallery image-popup-link text-center" style="background-image: url('/static/images/gallery-6.jpeg');">
                <span><i class="icon-search3"></i></span>
              </a>
              <a href="{% static 'images/gallery-7.jpeg' %}" class="gallery image-popup-link text-center" style="background-image: url('/static/images/gallery-7.jpeg');">
                <span><i class="icon-search3"></i></span>
              </a>
              <a href="{% static 'images/gallery-8.jpeg' %}" class="gallery image-popup-link text-center" style="background-image: url('/static/images/gallery-8.jpeg');">
                <span><i class="icon-search3"></i></span>
              </a>
            </div>
           
            <div class="side">
              <h2 class="sidebar-heading">Subscribe to our newsletter</h2>
              <div class="row">
                <div class="col-md-12 col-md-offset-0">
                  <div class="form-group">
                    <input type="text" class="form-control form-email text-center" id="email" placeholder="Enter your email">
                    <button type="submit" class="btn btn-primary btn-subscribe">Subscribe</button>
                  </div>
                </div>
                <p>
                  <ul class="colorlib-social-icons text-center">
                    <li><a href="#"><i class="icon-twitter"></i></a></li>
                    <li><a href="#"><i class="icon-facebook"></i></a></li>
                    <li><a href="#"><i class="icon-linkedin"></i></a></li>
                    <li><a href="#"><i class="icon-dribbble"></i></a></li>
                  </ul>
                </p>
              </div>
            </div>
          </aside> 
        </div>
      </div>
        {% endblock %}


{% endblock %}